// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using pkmnYPS.Repository;

#nullable disable

namespace pkmnYPS.Migrations
{
    [DbContext(typeof(PkmnContext))]
    partial class PkmnContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.14")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("pkmnYPS.Services.RepositoryModels.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ID");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("NVARCHAR(256)")
                        .HasColumnName("Email");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("NVARCHAR(256)")
                        .HasColumnName("Password");

                    b.Property<string>("Salt")
                        .IsRequired()
                        .HasColumnType("NVARCHAR(256)")
                        .HasColumnName("Salt");

                    b.HasKey("Id");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("pkmnYPS.Services.RepositoryModels.UserSearch", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ID");

                    b.Property<string>("SearchTerm")
                        .IsRequired()
                        .HasColumnType("NVARCHAR(256)")
                        .HasColumnName("SearchTerm");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("TIMESTAMP")
                        .HasColumnName("Timestamp");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("ID");

                    b.HasIndex("UserId");

                    b.ToTable("UserSearches");
                });

            modelBuilder.Entity("pkmnYPS.Services.RepositoryModels.UserSearch", b =>
                {
                    b.HasOne("pkmnYPS.Services.RepositoryModels.User", "User")
                        .WithMany("UserSearches")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("pkmnYPS.Services.RepositoryModels.User", b =>
                {
                    b.Navigation("UserSearches");
                });
#pragma warning restore 612, 618
        }
    }
}
